# use this file to set variables and paths that the program relies on

# path variable to ns-3 location
NS-3_PATH:

# path variable to script output location
SCRIPT_DEST:

# path to store various temporary output (like container config files)
TEMP_DIR:

# path variable to store container output
OUTPUT_DEST:

# default node type to use
NODE_TYPE: 